name: validate-internal
on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize]
jobs:
  internal:
    if: github.repository == github.event.pull_request.head.repo.full_name
    uses: ./.github/workflows/validate.yml
    secrets: inherit
